name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  build_and_test:
    strategy:
      matrix:
        target:
          - { name: Linux, os: ubuntu-latest, triple: x86_64-unknown-linux-gnu }
          - { name: macOS, os: macos-latest, triple: x86_64-apple-darwin }
          - { name: Windows, os: windows-latest, triple: x86_64-pc-windows-msvc }

    name: ${{ matrix.target.name }}

    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: checkout
        uses: actions/checkout@v2

      # Cache deps if not changed
      - name: cache deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target/debug
          key: ${{ matrix.target.os }}-${{ hashFiles('**/Cargo.lock') }}

      # Install Rust
      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target.triple }}

      # Run tests
      - name: test
        uses: actions-rs/cargo@v1
        timeout-minutes: 30
        with:
          command: test
          args: --no-fail-fast
